### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

# Use this format if using SIM (Server Visibility enabled) Machine Agent
metricPrefix: "Custom Metrics|SNMP Trap Receiver"

# Use this format if using plain Machine Agent
# This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO45/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|SNMP Trap Receiver"

# This "servers" section will not alter the behavior of the extension in any way, but is required by the implemented interface.
servers:
- host: http://www.localhost.com/
  name: localhost

# number of concurrent tasks
numberOfThreads: 1

# Machine Agent HTTP Listener
# All of the values shoule be strings wrapped in double quotes - see defaults for examples
machineAgentConnection:
  # host should remain as localhost, or perhaps loopback "127.0.0.1"
  host: "localhost"
  # port default matches Machine Agent default of "8293". If using different port for
  # the machine agent, e.g., passing JVM arg -Dmetric.http.listener.port=8080, port
  # value should be set as "8080"
  port: "8293"

# SNMP Trap Receiver Connection
# All of the values shoule be strings wrapped in double quotes - see defaults for examples
snmpConnection:
  # snmpProtocol can be "tcp" or "udp"
  snmpProtocol: "udp"
  snmpIP: "0.0.0.0"
  # Port values less than 1024 require Machine Agent to run as root/sudo
  snmpPort: "16200"
  # The below configurations are for v3 only
  snmpUsername: "username"
  # Auth Protocol Options are "MD5" or "SHA"
  snmpAuthProtocol: "MD5"
  snmpAuthPassPhrase: "authpassphrase"
  # Privacy/Encryption Protocol Options are "AES128", "AES192", "AES256", "DES", or "3DES"
  snmpPrivacyProtocol: "AES128"
  snmpPrivacyPassPhrase: "privacypassphrase"

# Custom Dashboard not implemented in this version of the extension.
#customDashboard:
#  enabled: false

# Events Service for Analytics Custom Events
# https://docs.appdynamics.com/display/PRO45/Analytics+Events+API
eventsServiceParameters:
  host: "<YOUR_CONTROLLER_URL_HERE>"
  port: <YOUR_EVENTS_SERVICE_PORT_HERE>
  globalAccountName: "<YOUR_GLOBAL_ACCOUNT_NAME_HERE>"
  eventsApiKey: "<YOUR_API_KEY_HERE"
  useSSL: false

# This configuration is not utilized in this current version of the extension.
#controllerInfo:
#  controllerHost: "192.168.86.40"
#  controllerPort: 8090
#  account: "customer1"
#  username: "user1"
#  password: "welcome"
#  encryptedPassword: ""
#  encryptionKey: ""
#  controllerSslEnabled: false
#  enableOrchestration: false
#  uniqueHostId: ""
#  accountAccessKey: ""
#  machinePath: ""
#  simEnabled: true
#  applicationName: ""
#  tierName: ""
#  nodeName: ""


#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier
#   convert
#   delta
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# These metrics are automatically generated by the extension, no configuration is required.

metrics:
- IncomingTraps:
    alias: "Incoming Traps"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    multiplier: ""
    convert:
    delta:
- OutgoingEvents:
    alias: "Outgoing Events"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    multiplier: ""
    convert:
    delta:
- HeartBeat:
    alias: "Heart Beat"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    multiplier: ""
    convert:
    delta:

enableHealthChecks: true # If not set, will be retrieved from "-Dappdynamics.agent.monitors.healthchecks.enable=true". Defaults to true.
