### ANY CHANGES TO THIS FILE DOES NOT REQUIRE A RESTART ###

#Use this format if using SIM (Server Visibility enabled) Machine Agent
metricPrefix: "Custom Metrics|SNMP Trap Receiver"

#Use this format if using plain Machine Agent
#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|SNMP Trap Receiver"

servers:
- host: http://www.localhost.com/
  name: localhost

# number of concurrent tasks
numberOfThreads: 1
#encryptionKey: welcome

#connection:
#  socketTimeout: 2000
#  connectTimeout: 2000
#  sslCertCheckEnabled: false
#  sslVerifyHostname: false
#  sslProtocols: ["TLSv1"]

#proxy:
#  uri: http://localhost:9090
#  username: proxyyuser
#  password: proxypassword

#taskSchedule:
#  numberOfThreads: 1
#  taskDelaySeconds: 300

# below section shows how to configure metrics you want to pull and how to list metric's qualifiers

#                                      List of metrics
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Glossary of terms(These terms are used as properties for each metric):
#   alias
#   aggregationType
#   timeRollUpType
#   clusterRollUpType                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
#   multiplier
#   convert
#   delta
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

metrics:
- IncomingRequests:
    alias: "Incoming Requests"
    aggregationType: "AVERAGE"
    timeRollUpType: "AVERAGE"
    clusterRollUpType: "INDIVIDUAL"
    multiplier: ""
    convert:
    delta:
#- OutgoingRequests:
#    alias: "Outgoing Requests"
#    aggregationType: "AVERAGE"
#    timeRollUpType: "AVERAGE"
#    clusterRollUpType: "INDIVIDUAL"
#    multiplier: "5"
#    convert:
#    delta:

enableHealthChecks: true # If not set, will be retrieved from "-Dappdynamics.agent.monitors.healthchecks.enable=true". Defaults to true.
